require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FMS_Helpdesk' do
  use_modular_headers!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-blob-util',    :path => '../node_modules/react-native-blob-util'
  pod 'RNFS', :path => '../node_modules/react-native-fs'


  target 'FMS_HelpdeskTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    system("IP=192.168.2.17; if [ -z \"$IP\" ]; then echo 'Network interface en0 is inactive or no IP address found. Skipping IP-related task.'; else echo 'Found IP address: $IP'; fi")
    # system("IP=$(ipconfig getifaddr en1); if [ -z \"$IP\" ]; then echo 'Network interface en0 is inactive or no IP address found. Skipping IP-related task.'; else echo 'Found IP address: $IP'; fi")

    # Regular post-install tasks
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
  end
end

